In [2]:
import numpy as np

In [5]:
al=[5,14,43,54,20]
a=np.array(al)
print(a)

[ 5 14 43 54 20]


In [7]:
print(np.sum(al))

136


In [8]:
print(np.mean(al))

27.2


In [10]:
print(np.median(al))

20.0


In [11]:
print(np.std(al))

18.36736235827017


In [12]:
print(np.sort(al))

[ 5 14 20 43 54]


In [13]:
np.random.random()

0.23448502887471845

In [14]:
np.random.rand(2,3)

array([[0.0350476 , 0.91897764, 0.98527217],
       [0.01386398, 0.60758718, 0.69975157]])

In [15]:
np.random.rand(2,3)

array([[0.89923786, 0.05382527, 0.23595062],
       [0.96601081, 0.14244116, 0.58107371]])

In [16]:
np.random.rand(2,3)


array([[0.88900303, 0.77348115, 0.49144814],
       [0.12026483, 0.15555181, 0.33279306]])

In [17]:
np.random.rand(2,3)

array([[0.6946032 , 0.11291397, 0.2434601 ],
       [0.09259052, 0.63170355, 0.78901879]])

In [18]:
np.random.randn(2,3)

array([[-1.98396367, -0.42452977, -0.27150456],
       [ 1.48533712, -0.54546642,  0.40845737]])

#### IF you want to know about the code or help about the code then click in the middle of parantheses and click shift+tab

###### random.random gives single value, random.rand gives value within 0 and 1, random.randn gives value within -1 and +1

###### random.randint gives random integer values
###### syntax= random.randint(0,n+1,size)

In [19]:
np.random.randint(0,101,100)

array([  7,   8,  51,   1,  49,  17,  52,   8,  85,  50,  32,  96,  49,
        17,  62,  49,  57,  71,   8,  60,  44,  12,  96,  28,  82,  71,
        18,  98,  46,  89,  29,  78,  41,  85,  69,  61,  80,  76, 100,
         9,  54,  93,  73,  87,  65,  84,  65,  57,  74,  12,  23,  55,
         9,  19,  67,  28,  22,  86,  34,  49,  34,  59,  51,  85,   6,
        45,  46,  56,  56,  56,  91,  68,  28,  68,  30,  60,  83,  46,
        16,  59,  96,   2,  74,   4,  22,  25,  63,  28,  24,  19,  43,
        20,  22,  66,  48,  97,  97,  75,  53,  46])

In [20]:
np.random.random(2,3)

TypeError: random() takes at most 1 positional argument (2 given)

In [21]:
np.random.random(size=3)

array([0.79911937, 0.71432688, 0.87382481])

In [22]:
np.random.rand(2,3,5)

array([[[0.40267062, 0.14582019, 0.76963671, 0.79574454, 0.37674289],
        [0.4127508 , 0.63234007, 0.74821467, 0.46430771, 0.39081075],
        [0.72588497, 0.33294644, 0.35140413, 0.50624877, 0.20173199]],

       [[0.35649997, 0.27346693, 0.78058557, 0.42915068, 0.65069535],
        [0.57634781, 0.67338883, 0.2067011 , 0.552745  , 0.04167604],
        [0.08848725, 0.15714072, 0.22756786, 0.43074201, 0.82239204]]])

In [23]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### default starting value will be 0

In [25]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

###### syntax= np.arange(start, stop, step, datatype)
###### datatype is optional

In [27]:
arr=np.arange(0,20,2,int)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
np.arange(0,51,5,int)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [29]:
np.arange(100,0,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [30]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [32]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [52]:
m=np.empty((3,3),dtype=int)
print(m)

[[        0         1         0]
 [  5570652      1192         0]
 [      768       519 923009264]]


###### by using empty we can fill values for 0 to infinity

In [54]:
n=np.full((3,3),fill_value=10)
print(n)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


###### by using full we can fill the given value to all the places in a matrix and the value has to be given in fill_value

In [56]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###### by using identity we can create a identity matrix

In [58]:
np.eye(N=3,M=4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
np.eye(N=5,M=6,k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

###### here N is no. of rows, M is no. of columns, k is to define main diagonal

In [63]:
a=np.arange(1,21)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [64]:
r=a.reshape(4,5)
r

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [65]:
k=a.reshape(2,10)
k


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [69]:
a.reshape(3,4)

ValueError: cannot reshape array of size 20 into shape (3,4)

In [71]:
sample_array=np.arange(0,11)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
sample_array[0]

0

In [73]:
sample_array[6]

6

In [74]:
sample_array[7]=11
sample_array

array([ 0,  1,  2,  3,  4,  5,  6, 11,  8,  9, 10])

In [75]:
sample_array[0:8]

array([ 0,  1,  2,  3,  4,  5,  6, 11])

In [76]:
sample_array[0:6:2]

array([0, 2, 4])

In [77]:
sample_array[8:0:-2]

array([8, 6, 4, 2])

In [78]:
sample_array[8:0:-1]

array([ 8, 11,  6,  5,  4,  3,  2,  1])

In [79]:
sample_array[7]=7
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###### in array indexing starting value is 0 by default

In [80]:
sample_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [81]:
sample_array[:5:-1]

array([10,  9,  8,  7,  6])

###### if we use -1 as step value without mentioning the start value it will automatically start from the ending